$ErrorActionPreference = 'Stop'

$RepoUrl = 'https://github.com/jin-li/ShellConfig.git'
$RepoDir = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'GitHub\ShellConfig'
$ThemeSource = Join-Path $RepoDir 'jinli.omp.json'

function Refresh-UserPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $env:Path = "$machinePath;$userPath"
}

function Test-MesloFont {
    $fontRoots = @(
        (Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Fonts'),
        (Join-Path $env:WINDIR 'Fonts')
    )
    foreach ($root in $fontRoots) {
        if (Test-Path $root) {
            if (Get-ChildItem -LiteralPath $root -Filter 'Meslo*' -File -ErrorAction SilentlyContinue) {
                return $true
            }
        }
    }
    return $false
}

if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    throw 'WinGet is required. Install App Installer from the Microsoft Store and rerun this script.'
}

if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {
    Write-Host 'Oh My Posh is already installed; skipping installation.'
} else {
    winget install JanDeDobbeleer.OhMyPosh --source winget --accept-package-agreements --accept-source-agreements
    Refresh-UserPath
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    winget install Git.Git --source winget --accept-package-agreements --accept-source-agreements
    Refresh-UserPath
} else {
    Write-Host 'Git is already installed; skipping installation.'
}

New-Item -ItemType Directory -Force -Path (Split-Path $RepoDir) | Out-Null
if (Test-Path (Join-Path $RepoDir '.git')) {
    git -C $RepoDir pull --ff-only
} elseif (Test-Path $RepoDir) {
    throw "$RepoDir exists but is not a Git checkout. Move it and rerun."
} else {
    git clone $RepoUrl $RepoDir
}

if (-not (Test-Path $ThemeSource -PathType Leaf)) {
    throw "Theme file not found: $ThemeSource"
}

$OhMyPoshCommand = Get-Command oh-my-posh -ErrorAction SilentlyContinue
if (-not $OhMyPoshCommand) {
    Refresh-UserPath
    $OhMyPoshCommand = Get-Command oh-my-posh -ErrorAction SilentlyContinue
}
if (-not $OhMyPoshCommand) {
    throw 'Oh My Posh was installed but is not available on PATH. Restart PowerShell and rerun this script.'
}
$OhMyPoshBin = Split-Path -Parent $OhMyPoshCommand.Source

$ProfileDir = Split-Path $PROFILE
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
$ProfileBackup = $null
if (Test-Path $PROFILE) {
    $ProfileBackup = "$PROFILE-pre-oh-my-posh-jinli"
    if (Test-Path $ProfileBackup) { $ProfileBackup += '-' + (Get-Date -Format 'yyyyMMdd-HHmmss') }
    Copy-Item $PROFILE $ProfileBackup
    Write-Host "Existing PowerShell profile copied to $ProfileBackup"
}

$ProfileLines = @(
    '# Generated by ShellConfig/install-oh-my-posh.ps1',
    "`$env:Path = `"$OhMyPoshBin;`$env:Path`"",
    "oh-my-posh init pwsh --config `"$ThemeSource`" | Invoke-Expression"
)
Set-Content -LiteralPath $PROFILE -Value $ProfileLines -Encoding UTF8

if (Test-MesloFont) {
    $FontMode = 'already available; skipped'
    Write-Host 'Meslo Nerd Font is already available; skipping installation.'
} else {
    $InstallFont = Read-Host 'Install the Meslo Nerd Font used by the Jinli theme? [y/N]'
    if ($InstallFont -match '^(y|yes)$') {
        oh-my-posh font install meslo
        $FontMode = 'installed'
        Write-Host 'Configure Windows Terminal to use "MesloLGM Nerd Font".'
    } else {
        $FontMode = 'skipped by user'
    }
}

Write-Host "`nConfiguration summary:"
Write-Host "  Repository:  $RepoDir"
Write-Host "  Theme:       $ThemeSource"
Write-Host "  Oh My Posh:  $OhMyPoshBin"
Write-Host "  PowerShell:  $PROFILE"
if ($ProfileBackup) { Write-Host "  Profile backup: $ProfileBackup" }
Write-Host "  Font:        MesloLGM Nerd Font ($FontMode)"
Write-Host "`nInstallation complete. Restart PowerShell or run: . `$PROFILE"
