$ErrorActionPreference = 'Stop'

$RepoUrl = 'https://github.com/jin-li/ShellConfig.git'
$DefaultRepoDir = if ($env:SHELL_CONFIG_DIR) {
    $env:SHELL_CONFIG_DIR
} else {
    Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'GitHub\ShellConfig'
}

$RequestedRepoDir = Read-Host "Clone ShellConfig to [$DefaultRepoDir]? Press Enter to confirm, or enter a different directory"
if ([string]::IsNullOrWhiteSpace($RequestedRepoDir)) {
    $RepoDir = $DefaultRepoDir
} elseif ($RequestedRepoDir -match '^~[\\/]') {
    $RepoDir = Join-Path $HOME $RequestedRepoDir.Substring(2)
} else {
    $RepoDir = [System.IO.Path]::GetFullPath($RequestedRepoDir)
}
Write-Host "Using ShellConfig directory: $RepoDir"

$ThemeSource = Join-Path $RepoDir 'jinli.omp.json'

function Refresh-UserPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $env:Path = "$machinePath;$userPath"
}

function Find-OhMyPosh {
    $command = Get-Command oh-my-posh -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Programs\oh-my-posh\bin\oh-my-posh.exe'),
        (Join-Path $env:LOCALAPPDATA 'Programs\oh-my-posh\oh-my-posh.exe'),
        (Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Links\oh-my-posh.exe'),
        (Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\oh-my-posh.exe'),
        (Join-Path $env:ProgramFiles 'oh-my-posh\bin\oh-my-posh.exe'),
        (Join-Path $env:ProgramFiles 'oh-my-posh\oh-my-posh.exe')
    )
    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return $candidate
        }
    }

    $packageRoot = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
    if (Test-Path $packageRoot) {
        $packageExecutable = Get-ChildItem -Path $packageRoot -Filter 'oh-my-posh.exe' -File -Recurse -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($packageExecutable) { return $packageExecutable.FullName }
    }
    return $null
}

function Test-MesloFont {
    $fontRoots = @(
        (Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Fonts'),
        (Join-Path $env:WINDIR 'Fonts')
    )
    foreach ($root in $fontRoots) {
        if (Test-Path $root) {
            if (Get-ChildItem -LiteralPath $root -Filter 'Meslo*' -File -ErrorAction SilentlyContinue) {
                return $true
            }
        }
    }
    return $false
}

if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    throw 'WinGet is required. Install App Installer from the Microsoft Store and rerun this script.'
}

$OhMyPoshExe = Find-OhMyPosh
if ($OhMyPoshExe) {
    Write-Host 'Oh My Posh is already installed; skipping installation.'
} else {
    Write-Host 'Oh My Posh was not found. Installing or repairing it with WinGet...'
    winget install --id JanDeDobbeleer.OhMyPosh --exact --source winget --force --accept-package-agreements --accept-source-agreements
    Refresh-UserPath
    $OhMyPoshExe = Find-OhMyPosh
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    winget install Git.Git --source winget --accept-package-agreements --accept-source-agreements
    Refresh-UserPath
} else {
    Write-Host 'Git is already installed; skipping installation.'
}

New-Item -ItemType Directory -Force -Path (Split-Path $RepoDir) | Out-Null
if (Test-Path (Join-Path $RepoDir '.git')) {
    git -C $RepoDir pull --ff-only
} elseif (Test-Path $RepoDir) {
    throw "$RepoDir exists but is not a Git checkout. Move it and rerun."
} else {
    git clone $RepoUrl $RepoDir
}

if (-not (Test-Path $ThemeSource -PathType Leaf)) {
    throw "Theme file not found: $ThemeSource"
}

if (-not $OhMyPoshExe) {
    Refresh-UserPath
    $OhMyPoshExe = Find-OhMyPosh
}
if (-not $OhMyPoshExe) {
    $wingetStatus = winget list --id JanDeDobbeleer.OhMyPosh --exact 2>&1 | Out-String
    throw "Could not locate the Oh My Posh executable after WinGet installation/repair. WinGet status:`n$wingetStatus`nTry opening a new PowerShell window and rerunning this script."
}
$OhMyPoshBin = Split-Path -Parent $OhMyPoshExe

$ProfileDir = Split-Path $PROFILE
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
$ProfileBackup = $null
$ManagedStart = '# >>> ShellConfig Oh My Posh >>>'
$ManagedEnd = '# <<< ShellConfig Oh My Posh <<<'
$ManagedProfileLines = @(
    $ManagedStart,
    "`$env:Path = `"$OhMyPoshBin;`$env:Path`"",
    "oh-my-posh init pwsh --config `"$ThemeSource`" | Invoke-Expression",
    $ManagedEnd
)

if (Test-Path $PROFILE) {
    $ExistingProfile = Get-Content -LiteralPath $PROFILE -Raw
    $ManagedPattern = '(?ms)^' + [regex]::Escape($ManagedStart) + '.*?^' + [regex]::Escape($ManagedEnd) + '\r?\n?'
    $LegacyPattern = '(?ms)^# Generated by ShellConfig/install-oh-my-posh\.ps1\r?\n(?:.*\r?\n){2}'
    if ($ExistingProfile -match $ManagedPattern) {
        $ManagedProfile = $ManagedProfileLines -join [Environment]::NewLine
        $UpdatedProfile = [regex]::Replace($ExistingProfile, $ManagedPattern, $ManagedProfile + [Environment]::NewLine)
        Write-Host 'Updated the existing ShellConfig Oh My Posh profile section.'
    } elseif ($ExistingProfile -match $LegacyPattern) {
        $ManagedProfile = $ManagedProfileLines -join [Environment]::NewLine
        $UpdatedProfile = [regex]::Replace($ExistingProfile, $LegacyPattern, $ManagedProfile + [Environment]::NewLine)
        Write-Host 'Migrated the previous ShellConfig Oh My Posh profile section.'
    } else {
        $ProfileBackup = "$PROFILE-pre-oh-my-posh-jinli"
        if (Test-Path $ProfileBackup) { $ProfileBackup += '-' + (Get-Date -Format 'yyyyMMdd-HHmmss') }
        Copy-Item $PROFILE $ProfileBackup
        Write-Host "Existing PowerShell profile copied to $ProfileBackup"
        $UpdatedProfile = $ExistingProfile.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + ($ManagedProfileLines -join [Environment]::NewLine) + [Environment]::NewLine
    }
} else {
    $UpdatedProfile = ($ManagedProfileLines -join [Environment]::NewLine) + [Environment]::NewLine
}
Set-Content -LiteralPath $PROFILE -Value $UpdatedProfile -Encoding UTF8

if (Test-MesloFont) {
    $FontMode = 'already available; skipped'
    Write-Host 'Meslo Nerd Font is already available; skipping installation.'
} else {
    $InstallFont = Read-Host 'Install the Meslo Nerd Font used by the Jinli theme? [y/N]'
    if ($InstallFont -match '^(y|yes)$') {
        & $OhMyPoshExe font install meslo
        $FontMode = 'installed'
        Write-Host 'Configure Windows Terminal to use "MesloLGM Nerd Font".'
    } else {
        $FontMode = 'skipped by user'
    }
}

Write-Host "`nConfiguration summary:"
Write-Host "  Repository:  $RepoDir"
Write-Host "  Theme:       $ThemeSource"
Write-Host "  Oh My Posh:  $OhMyPoshBin"
Write-Host "  PowerShell:  $PROFILE"
if ($ProfileBackup) { Write-Host "  Profile backup: $ProfileBackup" }
Write-Host "  Font:        MesloLGM Nerd Font ($FontMode)"
Write-Host "`nInstallation complete. Restart PowerShell or run: . `$PROFILE"
