#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_DIR="$SCRIPT_DIR"
POSH_DIR="$HOME/.config/oh-my-posh"
USER_ZSHRC="$HOME/.zshrc"
COMMON_ZSHRC="$REPO_DIR/.zshrc.common"
GENERATED_MARKER="# Generated by ShellConfig/install-oh-my-posh.sh"
LOCAL_PREFIX="${SHELL_CONFIG_PREFIX:-$HOME/.local}"

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'Error: %s\n' "$*" >&2; exit 1; }

if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
  die "Run this script as your normal user, not as root or with sudo."
fi

command -v git >/dev/null 2>&1 || die "git is required."
[[ -d "$REPO_DIR/.git" ]] || die "$REPO_DIR is not a Git checkout. Run install-oh-my-posh.sh first."

backup_path() {
  local backup="$HOME/.zshrc-pre-oh-my-posh-jinli"
  [[ ! -e "$backup" && ! -L "$backup" ]] || backup="$backup-$(date +%Y%m%d-%H%M%S)"
  printf '%s\n' "$backup"
}

detach_legacy_zshrc() {
  [[ -L "$USER_ZSHRC" ]] || return 0

  local target
  target=$(readlink "$USER_ZSHRC" 2>/dev/null || true)
  [[ "$target" == "$REPO_DIR/.zshrc" ]] || return 0

  local backup
  backup=$(backup_path)
  if [[ -f "$REPO_DIR/.zshrc" ]]; then
    cp -p "$REPO_DIR/.zshrc" "$backup"
    rm "$USER_ZSHRC"
    printf 'Previous shared .zshrc content backed up to %s\n' "$backup"
    if ! git -C "$REPO_DIR" diff --quiet -- .zshrc; then
      git -C "$REPO_DIR" restore --source=HEAD -- .zshrc
      printf 'Restored the repository .zshrc before updating\n'
    fi
  else
    mv "$USER_ZSHRC" "$backup"
    printf 'Previous shared .zshrc link moved to %s\n' "$backup"
  fi
}

create_local_zshrc() {
  {
    printf '%s\n' "$GENERATED_MARKER"
    printf '# Add machine-specific settings and tool initialization below.\n'
    printf 'source "%s"\n' "$COMMON_ZSHRC"
    if [[ -f "$HOME/.zshrc.local" ]]; then
      printf '\n# Backward compatibility for the former local configuration file.\n'
      printf '[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"\n'
    fi
  } > "$USER_ZSHRC"
}

find_oh_my_posh_dir() {
  local executable
  if command -v oh-my-posh >/dev/null 2>&1; then
    dirname "$(command -v oh-my-posh)"
    return 0
  fi
  for executable in "$LOCAL_PREFIX/bin/oh-my-posh" "$HOME/.local/bin/oh-my-posh" "$HOME/bin/oh-my-posh"; do
    if [[ -x "$executable" ]]; then
      dirname "$executable"
      return 0
    fi
  done
  return 1
}

ensure_oh_my_posh_path() {
  local executable_dir
  executable_dir=$(find_oh_my_posh_dir) || return 0
  export PATH="$executable_dir:$PATH"

  local path_comment="# Added by ShellConfig: keep Oh My Posh available in interactive Zsh."
  local path_line="export PATH=\"$executable_dir:\$PATH\""
  local common_line="source \"$COMMON_ZSHRC\""
  if [[ -f "$USER_ZSHRC" ]] && grep -Fq "$common_line" "$USER_ZSHRC"; then
    local temp_config="${USER_ZSHRC}.tmp.$$"
    awk -v path_comment="$path_comment" -v path_line="$path_line" -v common_line="$common_line" '
      $0 == path_comment || $0 == path_line { next }
      $0 == common_line && !inserted { print path_comment; print path_line; inserted = 1 }
      { print }
      END { if (!inserted) { print path_comment; print path_line } }
    ' "$USER_ZSHRC" > "$temp_config"
    mv "$temp_config" "$USER_ZSHRC"
  elif [[ ! -f "$USER_ZSHRC" ]] || ! grep -Fq "$executable_dir" "$USER_ZSHRC"; then
    {
      printf '\n%s\n' "$path_comment"
      printf '%s\n' "$path_line"
    } >> "$USER_ZSHRC"
  fi
}

log "Updating ShellConfig in $REPO_DIR"
detach_legacy_zshrc
git -C "$REPO_DIR" pull --ff-only
[[ -f "$COMMON_ZSHRC" ]] || die "Shared configuration not found: $COMMON_ZSHRC"

mkdir -p "$POSH_DIR"
ln -sfn "$REPO_DIR/jinli.omp.json" "$POSH_DIR/jinli.omp.json"

if [[ -L "$USER_ZSHRC" ]]; then
  backup=$(backup_path)
  mv "$USER_ZSHRC" "$backup"
  printf 'Previous .zshrc symlink moved to %s\n' "$backup"
fi

if [[ -e "$USER_ZSHRC" ]]; then
  if grep -Fq "$GENERATED_MARKER" "$USER_ZSHRC"; then
    printf 'ShellConfig local Zsh configuration already exists at %s\n' "$USER_ZSHRC"
  elif ! grep -Fq "source \"$COMMON_ZSHRC\"" "$USER_ZSHRC"; then
    backup=$(backup_path)
    mv "$USER_ZSHRC" "$backup"
    printf 'Previous .zshrc moved to %s\n' "$backup"
    create_local_zshrc
  fi
else
  create_local_zshrc
  printf 'Created local Zsh configuration at %s\n' "$USER_ZSHRC"
fi

ensure_oh_my_posh_path

log "Update complete"
printf '  Repository: %s\n' "$REPO_DIR"
printf '  Common Zsh: %s\n' "$COMMON_ZSHRC"
printf '  Local Zsh:  %s\n' "$USER_ZSHRC"
printf '  Theme:      %s\n' "$POSH_DIR/jinli.omp.json"
printf '\nRestart your terminal or run: exec zsh\n'
